dataset_params:
  image_shape: [64, 64, 3]
  root_dir: data/actions
  classes_list: data/actions.csv
  augmentation_param:
    flip_param: True
    select_frames_param:
      reflect_pad_time: True
      consequent: False
    crop_param:
      size: [64, 64]

log_params:
  log_freq_iter: 200
  cpk_freq_epoch: 1000

transfer_param:
  select_best_frame: True

model_params:
  detach_kp_generator: False
  detach_kp_discriminator: False
  common_params:
    num_kp: 10
    kp_variance: 0.01
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 16
     max_features: 128
     num_blocks: 5
  generator_params:
    deformation_module_params:
      block_expansion: 16
      max_features: 128
      num_blocks: 3
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
      num_group_blocks: 2
      camera_params: null
    main_module_params:
      block_expansion: 16
      max_features: 128
      num_blocks: 5
    kp_embedding_params:
      use_heatmap: True
  discriminator_params:
    block_expansion: 32
    use_kp: True
    max_features: 256
    num_blocks: 4

schedule_params:
  num_epochs: [5000, 500, 300, 200, 200, 200, 1000]
  frames_per_sample: [4, 8, 16, 32, 64, 100, 100]
  lr_generator: [2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-5]
  batch_size: [16, 16, 16, 8, 4, 2, 2]

loss_weights:
  reconstruction: [10, 10, 10, 10, 1]
  reconstruction_deformed: [10, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1
  tv: 0
  tv_border: 1
  kp_movement: 0
  var_reg: 0
  var_target: 0.01
