dataset_params:
  image_shape: [64, 64, 3]
  root_dir: data/actions
  classes_list: data/actions.csv
  augmentation_param:
    flip_param: True
#    rotation_param:
#      degrees: [-10, 10]
#    resize_param:
#      ratio : [1, 1.25]
#      interpolation: 'nearest'
    select_frames_param:
      reflect_pad_time: True
      consequent: True
#    crop_param:
#      size: [64, 64]

log_params:
  log_freq: 50
  cpk_freq: 1000

model_params:
  num_kp: 10
  kp_variance: 'learned'
  deformation_type: "predicted"
  num_channels: 3
  use_kp_embedding: True
  detach_deformation: True
  kp_extractor_module_params:
    temperature: 1
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_module_params:
    block_expansion: 32
    max_features: 64
    number_of_blocks: 3
    cumsum: False
  main_module_params:
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_embedding_params:
    use_difference: True
    difference_type: "absolute"
    features_per_kp: 4
  main_embedding_params:
    use_difference: False
    difference_type: "absolute"
    features_per_kp: 1
    learnable: False

schedule_params:
  num_epochs: [1000, 500, 300, 100, 100, 100, 1000]
  frames_per_sample: [4, 8, 16, 32, 64, 100, 100]
  lr: [1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-4]
  batch_size: [16, 16, 16, 8, 4, 2, 2]

loss_weights:
  reconstruction: 50
  reconstruction_deformed: 50
  reconstruction_grad: 0
  kp_movement: 0
  tv: 0
  tv_border: 1
  reconstruction_flow: 0
  kp_stationary: 1
  allowed_movement: 0.1
