dataset_params:
  offline_kp: False
  offline_flow: False
  image_shape: [64, 64, 3]
  root_dir: data/actions
  classes_list: data/actions.csv

log_params:
  log_freq: 50
  cpk_freq: 1000

model_params:
  num_kp: 10
  kp_gaussian_sigma: 0.1
  deformation_type: "predicted"
  num_channels: 3
  use_kp_embedding: True
  kp_extractor_module_params:
    temperature: 0.1
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_module_params:
    block_expansion: 32
    max_features: 64
    number_of_blocks: 3
  main_module_params:
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5

schedule_params:
  num_epochs: [1000, 1000, 1000, 1000, 1000, 1000, 1000]
  frames_per_sample: [4, 8, 16, 32, 50, 50, 50]
  lr: [1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-4, 1.0e-5]
  batch_size: [16, 16, 16, 16, 8, 8, 8]

loss_weights:
  reconstruction: 50
  reconstruction_deformed: 0
  reconstruction_grad: 0
  kp_movement: 0
  tv: 0
  tv_border: 1
  reconstruction_flow: 0

