dataset_params:
  root_dir: data/moving-gif-128
  classes_list: data/moving-gif.csv
  image_shape: [128, 128, 3]
  augmentation_params:
    flip_param:
      horizontal_flip: True
    crop_param:
      size: [128, 128]
    resize_param:
      ratio: [0.9, 1.1]
    jitter_param:
      hue: 0.5

model_params:
  common_params:
    num_kp: 10
    kp_variance: 'matrix'
    num_channels: 3
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     num_blocks: 6
  generator_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 6
    num_refinement_blocks: 4
    dense_motion_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 6
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
        heatmap_type: 'difference'
        norm_const: 1000
      num_group_blocks: 2
    kp_embedding_params:
      use_heatmap: True
      norm_const: 1000
      heatmap_type: 'difference'
  discriminator_params:
    kp_embedding_params:
      norm_const: 1000
    block_expansion: 32
    max_features: 256
    num_blocks: 4

train_params:
  detach_kp_generator: False
  detach_kp_discriminator: True
  num_epochs: 750
  epoch_milestones: [500]
  lr: 2.0e-4
  batch_size: 32
  loss_weights:
    reconstruction: [10, 10, 10, 10, 1]
    reconstruction_deformed: 0
    generator_gan: 1
    discriminator_gan: 1
  log_params:
    log_freq_iter: 200
    cpk_freq_epoch: 10

reconstruction_params:
  num_images: null
  format: '.gif'

transfer_params:
  num_pairs: 100
  format: '.gif'
  normalization_params:
    movement_mult: False
    move_location: True
    adapt_variance: False

prediction_params:
  rnn_params:
     num_features: 1024
     num_layers: 1
     dropout: 0
  num_epochs: 1000
  lr: 0.001
  batch_size: 256
  num_frames: 32
  init_frames: 1
  train_size: 5000
  format: '.gif'

visualizer_params:
  kp_size: 2
  draw_border: False
  colormap: 'gist_rainbow'

