dataset_params:
  root_dir: data/moving-gif-128
  classes_list: data/moving-gif.csv
  image_shape: [128, 128, 3]
  augmentation_param:
    flip_param:
      horizontal_flip: True
    crop_param:
      size: [128, 128]
    resize_param:
      ratio: [0.9, 1.1]
    jitter_param:
      hue: 0.5

log_params:
  log_freq_iter: 200
  cpk_freq_epoch: 100

transfer_params:
  num_pairs: 100
  format: '.gif'
  move_location: False
  movement_mult: False


model_params:
  detach_kp_generator: False
  detach_kp_discriminator: True
  common_params:
    num_kp: 10
    kp_variance: 'matrix'
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     num_blocks: 6
  generator_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 6
    num_refinement_blocks: 4
    deformation_module_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 6
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
        heatmap_type: 'difference'
        norm_const: 1000
      num_group_blocks: 0
    kp_embedding_params:
      use_heatmap: True
      norm_const: 1000
      heatmap_type: 'difference'
  discriminator_params:
    kp_embedding_params:
      norm_const: 1000
    block_expansion: 32
    max_features: 256
    num_blocks: 4


schedule_params:
  num_epochs: [500, 250]
  frames_per_sample: [1, 1]
  lr_generator: [2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-5]
  lr_kp_extractor: [2.0e-4, 2.0e-5]
  batch_size: [32, 32]

loss_weights:
  reconstruction: [10, 10, 10, 10, 1]
  reconstruction_deformed: [0, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1
