dataset_params:
  root_dir: data/nemo
  classes_list: null
  augmentation_param:
    rotation_param:
      degrees: [-45, 45]
    resize_param:
      ratio: [0.75, 1.25]
    flip_param:
      time_flip: False
      horizontal_flip: True
    crop_param:
      size: [64, 64]

log_params:
  log_freq_iter: 200
  cpk_freq_epoch: 200

transfer_params:
  num_pairs: 100
  format: '.mp4'
  movement_mult: True
  move_location: True

model_params:
  detach_kp_generator: False
  detach_kp_discriminator: True
  common_params:
    num_kp: 10
    kp_variance: 'matrix'
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 512
     num_blocks: 5
  generator_params:
    block_expansion: 32
    max_features: 512
    num_blocks: 5
    num_refinement_blocks: 4
    deformation_module_params:
      block_expansion: 32
      max_features: 512
      num_blocks: 5
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
        heatmap_type: 'difference'
      num_group_blocks: 2
    kp_embedding_params:
      use_heatmap: True
      heatmap_type: 'difference'
  discriminator_params:
    block_expansion: 32
    use_kp: True
    max_features: 256
    non_local_index: null
    num_blocks: 4

schedule_params:
  num_epochs: [500, 250]
  frames_per_sample: [1, 1]
  lr_generator: [2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-5]
  lr_kp_extractor: [2.0e-4, 2.0e-5]
  batch_size: [32, 32]

loss_weights:
  reconstruction: [10, 10, 10, 10, 1]
  reconstruction_deformed: [0, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1

prediction_params:
  module_params:
     num_kp: 10
     kp_variance: 'matrix'
     num_features: 1024
     num_layers: 1
     dropout: 0
  num_epochs: 5000
  lr: 0.001
  bs: 256
  num_frames: 32
  init_frames: 1
  train_size: -1
  format: '.mp4'
