data_dir: data/shapes
batch_size: 4
spatial_size: 64
num_channels: 3

num_kp: 1
kp_gaussian_sigma: 0.1
kp_extractor_temperature: 0.1

offline_kp: False
offline_flow: False
block_expansion: 16
deformation_type: "predicted"

lr: 1.0e-3

data_load_workers: 4
log_freq: 20
cpk_freq: 1000
num_iter: 10000

loss_weights:
  reconstruction: 50
  reconstruction_deformed: 50
  reconstruction_grad: 0
  kp_movement: 1
  tv: 0
  tv_border: 1
  reconstruction_flow: 0

