dataset_params:
  offline_kp: False
  offline_flow: False
  image_shape: [64, 64, 3]
  root_dir: data/shapes
  reflect_pad_train: False

log_params:
  log_freq: 20
  cpk_freq: 10000

model_params:
  num_kp: 10
  kp_variance: 0.1
  deformation_type: "predicted"
  num_channels: 3
  use_kp_embedding: True
  kp_extractor_module_params:
    temperature: 0.1
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_module_params:
    block_expansion: 16
    max_features: 64
    number_of_blocks: 3
    cumsum: False
  main_module_params:
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_embedding_params:
    use_difference: True
    difference_type: "absolute"
    features_per_kp: 4
  main_embedding_params:
    use_difference: False
    difference_type: "absolute"
    features_per_kp: 1

schedule_params:
  num_epochs: [1, 1, 1, 1, 1]
  frames_per_sample: [4, 8, 16, 32, 32]
  lr: [1.0e-3, 1.0e-3, 1.0e-3, 1.0e-3, 1.0e-4]
  batch_size: [2, 2, 2, 2, 2]

loss_weights:
  reconstruction: 50
  reconstruction_deformed: 50
  reconstruction_grad: 0
  kp_movement: 0
  tv: 0
  tv_border: 0
  reconstruction_flow: 0
  kp_stationary: 0
  allowed_movement: 0
