dataset_params:
  image_shape: [64, 64, 3]
  root_dir: data/shapes
  augmentation_param:
    flip_param:
      time_flip: True
      horizontal_flip: True
    select_frames_param:
      consequent: True
    crop_param:
      size: [64, 64]

log_params:
  log_freq_iter: 50
  cpk_freq_epoch: 1

transfer_params:
  num_pairs: 100
  format: '.gif'

model_params:
  detach_kp_generator: False
  detach_kp_discriminator: False
  common_params:
    num_kp: 5
    kp_variance: 'matrix'
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 16
     max_features: 128
     num_blocks: 5
  generator_params:
    block_expansion: 16
    max_features: 128
    num_blocks: 5
    num_refinement_blocks: 2
    deformation_module_params:
      block_expansion: 16
      max_features: 128
      num_blocks: 3
      use_mask: True
      use_correction: False
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
      num_group_blocks: 2
      camera_params: null
      camera_init: 0
    kp_embedding_params:
      use_heatmap: True
  discriminator_params:
    block_expansion: 32
    use_kp: True
    max_features: 128
    non_local_index: 1
    num_blocks: 3

schedule_params:
  num_epochs: [1, 1]
  frames_per_sample: [4, 4]
  lr_generator: [2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-5]
  lr_kp_extractor: [2.0e-4, 2.0e-5]
  batch_size: [4, 4]

loss_weights:
  reconstruction: [10, 10, 10, 10, 10]
  reconstruction_deformed: [10, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1
