dataset_params:
  image_shape: [64, 64, 3]
  root_dir: data/shapes
  augmentation_param:
    flip_param: True
    rotation_param:
      degrees: [-10, 10]
    resize_param:
      ratio : [0.75, 1.25]
      interpolation: 'nearest'
    select_frames_param:
      reflect_pad_time: True
      consequent: True
    crop_param:
      size: [64, 64]


log_params:
  log_freq: 20
  cpk_freq: 10000

generator_params:
  num_kp: 10
  kp_variance: 0.01
  deformation_type: "predicted"
  num_channels: 3
  use_kp_embedding: True
  detach_deformation: True
  kp_extractor_module_params:
    temperature: 0.1
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_module_params:
    block_expansion: 16
    max_features: 64
    number_of_blocks: 3
    cumsum: False
  main_module_params:
    block_expansion: 16
    max_features: 128
    number_of_blocks: 5
  deformation_embedding_params:
    use_difference: True
    difference_type: "absolute"
    features_per_kp: 4
    learnable: False
  main_embedding_params:
    use_difference: False
    learnable: False

discriminator_params:
  block_expansion: 32
  num_channels: 3
  max_features: 128
  number_of_blocks: 3

schedule_params:
  num_epochs: [1, 1, 1, 1, 1]
  frames_per_sample: [4, 8, 16, 32, 32]
  lr_generator: [2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-4, 2.0e-4, 2.0e-4, 2.0e-5]
  batch_size: [2, 2, 2, 2, 2]

loss_weights:
  reconstruction: [10, 10, 10, 10]
  reconstruction_deformed: [0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1
  tv: 0.1
  tv_border: 1
