dataset_params:
  root_dir: data/taichi
  classes_list: data/taichi.csv
  augmentation_param:
    flip_param:
      horizontal_flip: True
      time_flip: True
    crop_param:
      size: [64, 64]

log_params:
  log_freq_iter: 200
  cpk_freq_epoch: 1000


transfer_params:
  num_pairs: 300
  format: '.gif'
  movement_mult: False
  move_location: True


model_params:
  detach_kp_generator: False
  detach_kp_discriminator: True
  common_params:
    num_kp: 10
    kp_variance: 'matrix'
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 512
     num_blocks: 5
  generator_params:
    block_expansion: 32
    max_features: 512
    num_blocks: 5
    num_refinement_blocks: 4
    deformation_module_params:
      block_expansion: 32
      max_features: 512
      num_blocks: 5
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
        heatmap_type: 'difference'
        norm_const: 100
      num_group_blocks: 0
    kp_embedding_params:
      use_heatmap: True
      norm_const: 100
      heatmap_type: 'difference'
  discriminator_params:
    kp_embedding_params:
      norm_const: 100
    block_expansion: 32
    max_features: 256
    num_blocks: 4


schedule_params:
  num_epochs: [250, 125]
  frames_per_sample: [1, 1]
  lr_generator: [2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-5]
  lr_kp_extractor: [2.0e-4, 2.0e-5]
  batch_size: [32, 32]

loss_weights:
  reconstruction: [10, 10, 10, 10, 1]
  reconstruction_deformed: [0, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1

prediction_params:
  module_params:
     num_kp: 10
     kp_variance: 'matrix'
     num_features: 1024
     num_layers: 1
     dropout: 0
  num_epochs: 1000
  lr: 0.001
  bs: 256
  num_frames: 32
  init_frames: 1
  train_size: -1
  format: '.gif'
