dataset_params:
  root_dir: data/walking-gif
  classes_list: null
  image_shape: [128, 128, 3]
  augmentation_param:
    flip_param:
      horizontal_flip: True
    crop_param:
      size: [128, 128]

log_params:
  log_freq_iter: 200
  cpk_freq_epoch: 1000

transfer_params:
  num_pairs: 100
  format: '.gif'
  move_location: True
  movement_mult: True

model_params:
  detach_kp_generator: False
  detach_kp_discriminator: True
  common_params:
    num_kp: 10
    kp_variance: 'matrix'
    num_channels: 3
  kp_extractor_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 512
     num_blocks: 6
  generator_params:
    block_expansion: 32
    max_features: 512
    num_blocks: 6
    num_refinement_blocks: 0
    deformation_module_params:
      block_expansion: 32
      max_features: 512
      num_blocks: 6
      use_mask: True
      use_correction: True
      mask_embedding_params:
        use_heatmap: True
        use_deformed_appearance: True
        heatmap_type: 'difference'
      num_group_blocks: 2
      camera_params: null
    kp_embedding_params:
      use_heatmap: True
      heatmap_type: 'difference' 
  discriminator_params:
    block_expansion: 32
    use_kp: True
    max_features: 256
    non_local_index: null
    num_blocks: 4

schedule_params:
  num_epochs: [5000, 2500]
  frames_per_sample: [1, 1]
  lr_generator: [2.0e-4, 2.0e-5]
  lr_discriminator: [2.0e-4, 2.0e-5]
  lr_kp_extractor: [2.0e-4, 2.0e-5]
  batch_size: [32, 32]

loss_weights:
  reconstruction: [10, 10, 10, 10, 1]
  reconstruction_deformed: [10, 0, 0, 0, 0]
  generator_gan: 1
  discriminator_gan: 1
